serverConfig:
  node.environment: test
  http-server.http.port: 8080

routingRules:
  rulesEngineEnabled: False
  # rulesConfigPath: "gateway-ha/src/main/resources/rules/routing_rules.yml"

dataStore:
  jdbcUrl: jdbc:postgresql://localhost:5432/trino_gateway_db
  user: trino_gateway_db_admin
  password: P0stG&es
  driver: org.postgresql.Driver
  queryHistoryHoursRetention: 24

clusterStatsConfiguration:
  monitorType: INFO_API

# This can be adjusted based on the coordinator state
monitor:
  taskDelay: 1m
  clusterMetricsRegistryRefreshPeriod: 30s
