serverConfig:
  node.environment: test
  http-server.http.port: 8080
  tracing.enabled: true
  otel.exporter.endpoint: http://localhost:4318/v1/traces
  otel.exporter.protocol: http/protobuf

routingRules:
  rulesEngineEnabled: False
  # rulesConfigPath: "src/main/resources/rules/routing_rules.yml"

dataStore:
  jdbcUrl: jdbc:postgresql://${ENV:DB_HOSTNAME:localhost}:${ENV:DB_PORT:5432}/${ENV:DB_NAME:trino_gateway_db}
  user: ${ENV:DB_USER:trino_gateway_db_admin}
  password: ${ENV:DB_PASSWORD:P0stG&es}
  driver: org.postgresql.Driver
  queryHistoryHoursRetention: 24

clusterStatsConfiguration:
  monitorType: INFO_API

# This can be adjusted based on the coordinator state
monitor:
  taskDelay: 1m
  clusterMetricsRegistryRefreshPeriod: 30s
