httpConfig:
  node.environment: test
  http-server.http.port: 8080

routingRules:
  rulesEngineEnabled: False
  # rulesConfigPath: "src/main/resources/rules/routing_rules.yml"

dataStore:
  jdbcUrl: jdbc:postgresql://postgres:5432/trino_gateway_db
  user: trino_gateway_db_admin
  password: P0stG&es
  driver: org.postgresql.Driver
  queryHistoryHoursRetention: 24

clusterStatsConfiguration:
  monitorType: INFO_API

modules:
  - io.trino.gateway.ha.module.HaGatewayProviderModule
  - io.trino.gateway.ha.module.ClusterStateListenerModule
  - io.trino.gateway.ha.module.ClusterStatsMonitorModule

managedApps:
  - io.trino.gateway.ha.clustermonitor.ActiveClusterMonitor
