name: Release new version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check if release is running from main
        run: |
          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
            echo "Release is only allowed from main branch"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install java
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.RELEASE_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: 'maven'

      - name: Configure git
        run: |
          git config user.name "Trino Release"
          git config user.email "trino-bot@trino.io"

      - name: Lock branch before release
        uses: github/lock@v3
        id: release-lock
        with:
          mode: lock

      - name: Run mvn release:prepare
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASE_GPG_PASSPHRASE }}
        run: |
          mvn -B release:prepare -Poss-release

      - name: Determine release version
        run: |
          export VERSION=$(grep 'scm.tag=' release.properties | cut -d'=' -f2)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Releasing version: ${VERSION}"

      - name: Run mvn release:perform to local staging
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASE_GPG_PASSPHRASE }}
        run: |
          mvn -B release:perform -Poss-release

      - name: Display git status and history
        run: |
          git status
          git log --oneline -n 2

      - name: Run njord:validate
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASE_GPG_PASSPHRASE }}
          MAVENCENTRAL_USERNAME: ${{ vars.RELEASE_MAVEN_CENTRAL_USERNAME }}
          MAVENCENTRAL_PASSWORD: ${{ secrets.RELEASE_MAVEN_CENTRAL_TOKEN }}
        run: |
          mvn njord:list
          mvn njord:status
          mvn njord:validate

      - name: Run njord:publish
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASE_GPG_PASSPHRASE }}
          MAVENCENTRAL_USERNAME: ${{ vars.RELEASE_MAVEN_CENTRAL_USERNAME }}
          MAVENCENTRAL_PASSWORD: ${{ secrets.RELEASE_MAVEN_CENTRAL_TOKEN }}
        run:
          mvn njord:publish -Poss-release

      - name: Push git changes
        run: |
          git status
          git describe
          git push origin main
          git push origin --tags

      - name: Unlock branch after a release
        uses: github/lock@v3
        id: release-unlock
        with:
          mode: unlock

      - name: Create release notes
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release create "${VERSION}" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REPOSITORY#*/} ${VERSION}" \
              --generate-notes
