name: Stale PR tracking

on:
  schedule:
    - cron: '0 17 * * 1-5' # 9am UTC-8 on weekdays

permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository == 'trinodb/trino-gateway'
    steps:
      - uses: actions/stale@v10.2.0
        with:
          # PRs
          stale-pr-message: 'This pull request has gone a while without any activity. Ask for help on #trino-gateway-dev on Trino slack.'
          days-before-pr-stale: 21
          days-before-pr-close: 21
          close-pr-message: 'Closing this pull request, as it has been stale for six weeks. Feel free to re-open at any time.'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'stale-ignore'
          exempt-draft-pr: false
          # Issues
          stale-issue-message: 'This issue has gone a while without any activity. Ask for help on #trino-gateway-dev on Trino slack.'
          days-before-issue-stale: 21
          days-before-issue-close: 21
          close-issue-message: 'Closing this issue, as it has been stale for six weeks. Feel free to re-open at any time.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'stale-ignore,roadmap'
          # Global settings
          start-date: '2020-01-01T00:00:00Z'
          operations-per-run: 200
  
